version: '3.10'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: 'UTC'
      PGTZ: 'UTC'
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  ducubot:
    image: andriihorobets/docubot:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    env_file: .env
    environment:
      DB_HOST: pdf_to_llama-postgres-1
      REDIS_HOST: pdf_to_llama-redis-1
  alembic:
    build:
      context: .
    depends_on:
      - postgres
    entrypoint: alembic upgrade head
    environment:
      DATABASE_URL: "postgresql://${DB_NAME}:${DB_PASSWORD}@db:5432/${DB_NAME}"  

volumes:
  db-data:
