"""Add user token

Revision ID: 1af7f21ebe69
Revises: b355a97878f6
Create Date: 2023-10-06 21:25:44.318803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af7f21ebe69'
down_revision = 'b355a97878f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
