"""user_tokens

Revision ID: 780de16559cf
Revises: 1af7f21ebe69
Create Date: 2023-10-07 20:42:31.234722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780de16559cf'
down_revision = '1af7f21ebe69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_user_tokens', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_tokens')
    # ### end Alembic commands ###
